org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
org.gradle.workers.max=2

minecraft_version=26.3-snapshot-2
minecraft_dependency_version=>=26.3-alpha.2 <26.3
loader_version=0.19.3
fabric_version=0.154.0+26.3

mod_version=1.0.0
maven_group=io.github.wu_xiao_ya.keyboard_wizard_ce.fabric
archives_base_name=keyboard-wizard-ce-fabric-26.3-snapshot-2
