name: Build

on:
  push:
    branches:
      - "ce/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --stacktrace

      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: keyboard-wizard-ce-forge-1.12.2
          path: build/libs/*.jar
